==== Envelope

[abstract]
The envelope is the transport container of a message.

....
envelope: {
  header: {
    "sender" : "string",  // the sender of this message
    "recipients" : "string[]", // the recipients of the message
    "messageid" : "string", // globally unique message id
    "expires" : "datetime", // should be dropped if older than this.
    "message_type" : "string" // the type of the message body
    "api_version" : "string",
    "send_delivery_receipt": "bool", // send receipt when delivered to recipient
    "send_transport_notification": "bool", // send notifications from intermediate hubs

  },
  "transitinformation" :
  {
    "path" : "string[]",  // list of message brokers that has handled this message
    "timetolive" : "int", // this value is decreased by each broker and message is dropped if it reaches 0 without delivery
  },
  "message" :
  {
    "message data",
    ...
  },
  "encryption" :
  {
    "keys" : "dictionary of keys", // dictionary of keys used to decrypt the mesage data, one encrypted key for each recipient
    "cipher" : "string", // the cipher used to encrypt the data
  }
  "signature" : "base64 encoded signature over header and message"
}
....

Example message

....
envelope : {
    header: {
      sender : "monarch@acme.com",
      recipients : ["queen@xyz.com","prince@abc.com"],
      messageid : "12356-1234-12345@acme.com",
      expires : "2020-06-01T14:00:00+UTC",
      message_type : "hello",
      api_version : "0.1"
    },
    transitinformation:{
      path:["broker@acme.com", "publicendpoint@acme.com"],
      timetolive : 28
    },
    message : {
        text : "hello"
    },
    encryption : null,
    signature : "9sd18313812ab3s3=="
}
....
